// Mock data for K12 Standards Interface prototyping

import { K12StandardsData } from './K12StandardsInterface.types';

export const mockK12Data: K12StandardsData = {
  standards: [
    {
      id: 'std-001',
      name: 'Causes of the Civil War',
      domain: 'us_history',
      description: 'Understanding the political, economic, and social causes of the American Civil War',
      classCount: 3,
      studentCount: 72,
    },
    {
      id: 'std-002',
      name: 'Reconstruction Era',
      domain: 'us_history',
      description: 'Analyzing policies and outcomes of the Reconstruction period',
      classCount: 3,
      studentCount: 72,
    },
    {
      id: 'std-003',
      name: 'Industrialization Impact',
      domain: 'us_history',
      description: 'Examining effects of industrialization on American society',
      classCount: 2,
      studentCount: 48,
    },
    {
      id: 'std-004',
      name: 'Argument Construction',
      domain: 'ap_seminar',
      description: 'Building and evaluating evidence-based arguments',
      classCount: 2,
      studentCount: 56,
    },
    {
      id: 'std-005',
      name: 'Question and Exploration',
      domain: 'ap_seminar',
      description: 'Developing effective research questions',
      classCount: 2,
      studentCount: 56,
    },
    {
      id: 'std-006',
      name: 'Evidence Evaluation',
      domain: 'ap_seminar',
      description: 'Assessing credibility and relevance of sources',
      classCount: 2,
      studentCount: 56,
    },
    {
      id: 'std-007',
      name: 'Rhetorical Analysis',
      domain: 'english_lit',
      description: 'Analyzing author purpose and rhetorical devices',
      classCount: 4,
      studentCount: 96,
    },
    {
      id: 'std-008',
      name: 'Literary Interpretation',
      domain: 'english_lit',
      description: 'Developing textual evidence-based literary interpretations',
      classCount: 4,
      studentCount: 96,
    },
  ],

  classes: [
    {
      id: 'class-001',
      name: 'AP US History Period 1',
      departmentId: 'dept-001',
      departmentName: 'History',
      studentCount: 24,
      standardCount: 8,
      avgMasteryLevel: 2.8,
    },
    {
      id: 'class-002',
      name: 'AP US History Period 3',
      departmentId: 'dept-001',
      departmentName: 'History',
      studentCount: 24,
      standardCount: 8,
      avgMasteryLevel: 3.1,
    },
    {
      id: 'class-003',
      name: 'AP US History Period 5',
      departmentId: 'dept-001',
      departmentName: 'History',
      studentCount: 24,
      standardCount: 8,
      avgMasteryLevel: 2.9,
    },
    {
      id: 'class-004',
      name: 'AP Seminar Section A',
      departmentId: 'dept-002',
      departmentName: 'English',
      studentCount: 28,
      standardCount: 6,
      avgMasteryLevel: 2.6,
    },
    {
      id: 'class-005',
      name: 'AP Seminar Section B',
      departmentId: 'dept-002',
      departmentName: 'English',
      studentCount: 28,
      standardCount: 6,
      avgMasteryLevel: 2.7,
    },
    {
      id: 'class-006',
      name: 'AP English Literature',
      departmentId: 'dept-002',
      departmentName: 'English',
      studentCount: 32,
      standardCount: 7,
      avgMasteryLevel: 3.2,
    },
    {
      id: 'class-007',
      name: 'Honors English Literature',
      departmentId: 'dept-002',
      departmentName: 'English',
      studentCount: 32,
      standardCount: 7,
      avgMasteryLevel: 3.3,
    },
  ],

  studentProgress: [
    {
      studentId: 'stu-001',
      studentName: 'Alex Chen',
      cohort: 'ELL',
      masteryByStandard: {
        'std-001': 3,
        'std-002': 2,
        'std-003': 3,
        'std-004': 2,
        'std-005': 2,
        'std-006': 2,
        'std-007': 3,
        'std-008': 3,
      },
    },
    {
      studentId: 'stu-002',
      studentName: 'Bailey Rodriguez',
      cohort: 'IEP',
      masteryByStandard: {
        'std-001': 2,
        'std-002': 2,
        'std-003': 2,
        'std-004': 1,
        'std-005': 2,
        'std-006': 1,
        'std-007': 2,
        'std-008': 2,
      },
    },
    {
      studentId: 'stu-003',
      studentName: 'Cameron Smith',
      cohort: '',
      masteryByStandard: {
        'std-001': 4,
        'std-002': 4,
        'std-003': 3,
        'std-004': 4,
        'std-005': 3,
        'std-006': 4,
        'std-007': 4,
        'std-008': 4,
      },
    },
    {
      studentId: 'stu-004',
      studentName: 'Diana Johnson',
      cohort: 'ELL',
      masteryByStandard: {
        'std-001': 2,
        'std-002': 3,
        'std-003': 2,
        'std-004': 2,
        'std-005': 3,
        'std-006': 2,
        'std-007': 3,
        'std-008': 3,
      },
    },
    {
      studentId: 'stu-005',
      studentName: 'Ethan Lee',
      cohort: '504',
      masteryByStandard: {
        'std-001': 3,
        'std-002': 3,
        'std-003': 3,
        'std-004': 3,
        'std-005': 3,
        'std-006': 3,
        'std-007': 3,
        'std-008': 3,
      },
    },
    {
      studentId: 'stu-006',
      studentName: 'Fiona Murphy',
      cohort: '',
      masteryByStandard: {
        'std-001': 4,
        'std-002': 3,
        'std-003': 4,
        'std-004': 3,
        'std-005': 4,
        'std-006': 3,
        'std-007': 4,
        'std-008': 4,
      },
    },
    {
      studentId: 'stu-007',
      studentName: 'Gabriel Martinez',
      cohort: 'IEP',
      masteryByStandard: {
        'std-001': 2,
        'std-002': 2,
        'std-003': 1,
        'std-004': 2,
        'std-005': 2,
        'std-006': 2,
        'std-007': 2,
        'std-008': 2,
      },
    },
    {
      studentId: 'stu-008',
      studentName: 'Hannah Brown',
      cohort: 'ELL',
      masteryByStandard: {
        'std-001': 3,
        'std-002': 3,
        'std-003': 2,
        'std-004': 3,
        'std-005': 2,
        'std-006': 3,
        'std-007': 3,
        'std-008': 3,
      },
    },
  ],

  cohorts: [
    {
      id: 'cohort-ell',
      name: 'English Language Learners',
      description: 'Students learning English as a second language',
      studentCount: 3,
      avgMasteryLevel: 2.7,
    },
    {
      id: 'cohort-iep',
      name: 'Students with IEPs',
      description: 'Students with Individualized Education Plans',
      studentCount: 2,
      avgMasteryLevel: 2.0,
    },
    {
      id: 'cohort-504',
      name: '504 Plan',
      description: 'Students with 504 accommodations',
      studentCount: 1,
      avgMasteryLevel: 3.0,
    },
  ],
};
